services:
  # Backend Service
  - type: web
    name: backend
    env: docker
    rootDir: ./backend
    plan: free # Can be changed in dashboard
    branch: Develop # Adjust if using a different branch
    envVars:
      - key: PORT
        value: 8080
      - key: JDBC_DATABASE_URL
        sync: false # Requires manual input in Dashboard
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true

  # Frontend Service
  - type: web
    name: frontend
    env: docker
    rootDir: ./frontend
    plan: free
    branch: main
    envVars:
      - key: PORT
        value: 80
